version: "3.6"
services:
  master:
    image: mengluo668/hadoop:2.9.1
    command: "bin/hdfs namenode -format && sbin/start-all.sh"
    hostname: master.idianyou.com
    container_name: master.idianyou.com
    volumes:
      - ${PWD}/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ${PWD}/hdfs-site.xml:/hadoop/etc/hadoop/hdfs-site.xml
      - ${PWD}/yarn-site.xml:/hadoop/etc/hadoop/yarn-site.xml
      - ${PWD}/mapred-site.xml:/hadoop/etc/hadoop/mapred-site.xml
      - ${PWD}/slaves:/hadoop/etc/hadoop/slaves
    ports:
      - 50070:50070
      - 8088:8088
    networks: 
      webnet:
        aliases:
          - "master.idianyou.com"
  worker1:
    image: mengluo668/hadoop:2.9.1
    hostname: worker1.idianyou.com
    container_name: worker1.idianyou.com
    volumes:
      - ${PWD}/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ${PWD}/yarn-site.xml:/hadoop/etc/hadoop/yarn-site.xml
    restart: always
    networks: 
      webnet:
        aliases:
          - "worker1.idianyou.com"
  worker2:
    image: mengluo668/hadoop:2.9.1
    hostname: worker2.idianyou.com
    container_name: worker2.idianyou.com
    volumes:
      - ${PWD}/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ${PWD}/yarn-site.xml:/hadoop/etc/hadoop/yarn-site.xml
    restart: always
    networks: 
      webnet:
        aliases:
          - "worker2.idianyou.com"
networks:
  webnet: